config/routes.rb
Rails.application.routes.draw do
  resources :weight_histories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', to: 'top#index'

  get '/users', to: 'users#index', as: "users"
  get '/users/:id', to: 'users#show', as: "user"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :weight_histories
end

app/models/weight_history.rb
class WeightHistory < ApplicationRecord
  belongs_to :user

  before_validation :set_memo

  validates :user_id, presence: { message: "ユーザーを入力してください" }
  validates :memo, length: { maximum: 255, too_long: "メモは最大%{count}文字以内で入力してください" }
  validate :weight_validate

  def weight_validate
    if weight < 1
      errors.add(:weight, "体重が正しくありません")
    end
  end

  def set_memo 
    if memo.nil?
      self.memo = "なし"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/top_controller.rb
class TopController < ActionController::Base
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params["id"])
  end
end

app/controllers/weight_histories_controller.rb
class WeightHistoriesController < ApplicationController
  before_action :set_weight_history, only: %i[ show edit update destroy ]

  # GET /weight_histories or /weight_histories.json
  def index
    @weight_histories = WeightHistory.all
  end

  # GET /weight_histories/1 or /weight_histories/1.json
  def show
  end

  # GET /weight_histories/new
  def new
    @weight_history = WeightHistory.new
  end

  # GET /weight_histories/1/edit
  def edit
  end

  # POST /weight_histories or /weight_histories.json
  def create
    @weight_history = WeightHistory.new(weight_history_params)

    respond_to do |format|
      if @weight_history.save
        format.html { redirect_to @weight_history, notice: "Weight history was successfully created." }
        format.json { render :show, status: :created, location: @weight_history }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @weight_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weight_histories/1 or /weight_histories/1.json
  def update
    respond_to do |format|
      if @weight_history.update(weight_history_params)
        format.html { redirect_to @weight_history, notice: "Weight history was successfully updated." }
        format.json { render :show, status: :ok, location: @weight_history }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @weight_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weight_histories/1 or /weight_histories/1.json
  def destroy
    @weight_history.destroy
    respond_to do |format|
      format.html { redirect_to weight_histories_url, notice: "Weight history was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weight_history
      @weight_history = WeightHistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def weight_history_params
      params.require(:weight_history).permit(:user_id, :weight, :memo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weight_histories_helper.rb
module WeightHistoriesHelper
  def weight_comment(weight)
    if weight < 20
      "#{weight} (やせ型)"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutorial</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/index.html.erb
<h1>Hello rails</h1>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>

<% @users.each do |user| %>
  <%= link_to user.name, user_path(id: user.id) %><br>
<% end %>

app/views/users/show.html.erb
<h1>ユーザー詳細情報</h1>

<%= @user.name %><br>
<%= @user.age %>歳

<%= link_to "戻る", users_path %> 

app/views/weight_histories/_form.html.erb
<%= form_with(model: weight_history) do |form| %>
  <% if weight_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(weight_history.errors.count, "error") %> prohibited this weight_history from being saved:</h2>

      <ul>
        <% weight_history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.number_field :weight %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_field :memo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/weight_histories/edit.html.erb
<h1>Editing Weight History</h1>

<%= render 'form', weight_history: @weight_history %>

<%= link_to 'Show', @weight_history %> |
<%= link_to 'Back', weight_histories_path %>

app/views/weight_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Weight Histories</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Weight</th>
      <th>Memo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weight_histories.each do |weight_history| %>
      <tr>
        <td><%= weight_history.user_id %></td>
        <td><%= weight_history.weight %></td>
        <td><%= weight_history.memo %></td>
        <td><%= link_to 'Show', weight_history %></td>
        <td><%= link_to 'Edit', edit_weight_history_path(weight_history) %></td>
        <td><%= link_to 'Destroy', weight_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weight History', new_weight_history_path %>

app/views/weight_histories/new.html.erb
<h1>New Weight History</h1>

<%= render 'form', weight_history: @weight_history %>

<%= link_to 'Back', weight_histories_path %>

app/views/weight_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @weight_history.user.name %>
</p>

<p>
  <strong>Weight:</strong>
  <%= weight_comment(@weight_history.weight) %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @weight_history.memo %>
</p>

<%= link_to 'Edit', edit_weight_history_path(@weight_history) %> |
<%= link_to 'Back', weight_histories_path %>